# === PLUGINS ===
plugins:
   - jekyll-octicons
#   - "jekyll-github-metadata"
# ===============

collections:
  notes:
    output: true
    permalink: /:path:output_ext

# === METADATA (site.*)

url: "" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog

title: "Alessandro Dicosola' repositories" # the name of your site, e.g. ACME Corp.

contacts:
 - name: "github"
   url: "https://github.com/alessandrodicosola"

 - name: "linkedin"
   url: "https://linkedin.com/in/alessandrodicosola"
  


repositories:
  exclude:
    - alessandrodicosola.github.io
    - IntrusionDetection
    - lsqls
    - rsd
    - rsc
    # TODO: Remove froim hidden
    - NAI
  
  frameworks:
    - pytorch
    - keras
    - sql


# ===================  
